CREATE TABLE "capella_check_in" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "capella_check_in_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"habitId" integer NOT NULL,
	"date" date NOT NULL,
	"note" text,
	"backfilled" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "capella_check_in_habit_date_unique" UNIQUE("habitId","date")
);
--> statement-breakpoint
CREATE TABLE "capella_habit_target" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "capella_habit_target_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"habitId" integer NOT NULL,
	"value" integer NOT NULL,
	"effectiveFrom" date NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "capella_habit_target_habit_effective_from_unique" UNIQUE("habitId","effectiveFrom"),
	CONSTRAINT "capella_habit_target_value_check" CHECK ("capella_habit_target"."value" >= 1)
);
--> statement-breakpoint
CREATE TABLE "capella_habit" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "capella_habit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"startDate" date NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "capella_period_skip" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "capella_period_skip_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"habitId" integer NOT NULL,
	"periodStart" date NOT NULL,
	"reason" text,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "capella_period_skip_habit_period_unique" UNIQUE("habitId","periodStart"),
	CONSTRAINT "capella_period_skip_reason_check" CHECK ("capella_period_skip"."reason" in ('tired', 'sick', 'busy', 'travel'))
);
--> statement-breakpoint
DROP TABLE "sirius_post" CASCADE;--> statement-breakpoint
ALTER TABLE "capella_check_in" ADD CONSTRAINT "capella_check_in_habitId_capella_habit_id_fk" FOREIGN KEY ("habitId") REFERENCES "public"."capella_habit"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "capella_habit_target" ADD CONSTRAINT "capella_habit_target_habitId_capella_habit_id_fk" FOREIGN KEY ("habitId") REFERENCES "public"."capella_habit"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "capella_period_skip" ADD CONSTRAINT "capella_period_skip_habitId_capella_habit_id_fk" FOREIGN KEY ("habitId") REFERENCES "public"."capella_habit"("id") ON DELETE cascade ON UPDATE no action;